### ISSUE TITLE
Hardware TODOs pre ARCHE

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#371]
### Tasks Turcan & Kappi
- [x] GPS interference testing on the box + on Dodo -> this task is blocking for Thomas to continue working on the final protection and mounting
- [x] Mounting of Antennas in Dual GPS setup on the box
- [ ] Mounting of Antennas in Dual GPS setup on the Dodo - we should here at first test the current wood setup
- [x] CPT7 - Basilisk mounting plate (just checking if this is all good)

### Thomas
- [ ] Can we mount the box on Titan?
- [ ] Is the roll-over cage solution satisfying 
- [x] (blocked) - Final GPS mounting in Backpack solution
- [ ] (blocked) - Final GPS mounting on Robot

### Ulrich
- [x] Water-tight alpha sense camera lenses -> maybe create updated 3D printed holder of the glass without the corners as discussed in the meeting (Ulrich)
- [x] Integration into the backpack solution - I will sent a link for a good backpack and did not manage yesterday to buy one 

### Jannes
- [x] Basilisk proper cable to support ethernet + triggering remove the legacy AP20 one 

### Matthias
- [ ] GMSL cables ordering (check here with Matthias if everything is on track)
- [x] Ordering new USB C connector incorrect length that we can screw onto CPT7 https://www.digitec.ch/de/s1/product/startech-com-3ft-1m-top-screw-locking-usb-c-cable-10gbps-usb-3132-gen-2-type-c-cable-100w-5a-power-d-17704004
- [ ] Currently, something is still wrong with the USB-C to USB-C, which prohibits us from powering it check with Matthias what we can do about it - or check if Leica can do something for us
- [x] Jonas -> USB C cable and sent to Matthias
- [ ] Integration of RGB LEDs + Software Buttons for start / stopping
- [ ] Integration of a hard reset button if possible on the Traco to stop-start powering things
- [x] New Rasberry Pi Board
- [x] Include Honeywell 
- [x] (very low priority) Power tool battery integration
