### ISSUE TITLE
Week 38 - Goals 

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#564]
# Existing Issues to address:

## Jonas:
- [x] AP20 make a verification run if timestamps are always good / start / stop totalstation - lose connection - lose line of sight / lose Bluetooth.
- [ ] Improve ptp synchronization with delay compensation
- [ ] TimeSync analysis script - improve to allow for multi-imu alignment.
- [ ] Start-stop recording zest including ZED2i 
- [x] Verify that autostarts works
https://github.com/leggedrobotics/grand_tour_box/issues/540
- [x] Hesai Postprocessing auto integration https://github.com/leggedrobotics/grand_tour_box/issues/555
- [ ] Ground Turth with Julian https://github.com/leggedrobotics/grand_tour_box/issues/558
- [x] Fixing the recording error with the magic docker failure
- [x] Integrating the latest branch on the adis and adapting the changes. 
- [ ] Fix ADIS https://github.com/leggedrobotics/grand_tour_box/issues/553
- [ ] Documentation of PI https://github.com/leggedrobotics/grand_tour_box/issues/539
- [ ] STIM https://github.com/leggedrobotics/grand_tour_box/issues/535

## Frank:
- [x] Fix the livox merging issue https://github.com/leggedrobotics/livox_ros_driver2/pull/2
- [ ] Postprocessing CPT7 data https://github.com/leggedrobotics/grand_tour_box/issues/536
- [ ] Postprocess PTP and Allen Variance https://github.com/leggedrobotics/grand_tour_box/issues/563
- [x] Finalize URDF / frame verification https://github.com/leggedrobotics/grand_tour_box/issues/530
- [ ] Run camera-camera calibration live with visual coverage feedback
- [ ] Merging the tf bag of the robot and the box 

### Improvements

- [ ] **Jetson:** rebuilt jetson docker container with new workspace and check in changes
- [x] **PI** Integrate box_health onto pi

### Verifications runs

- [ ] Check adjust all the frames correctly in the tf and urdf and postprocessing
- [ ] Do Stefan Leutenegger datacollection
- [x] Verify cpt7 span numbers
- [x] Verify all rosbags with topic_freq
- [x] Integration test with ANYmal tomorrow

### Organization
- [ ] kleinkram
- [ ] wegpage GrandTour
- [ ] Friday paper discussion with Cedric 4pm - Hardware grand tour paper part
- [ ] Visualizations of box in CAD / temperature  FoV / Rendering
- [ ] Stefan Leutenegger - Hongkong - two GoogleDrive Links
- [ ] Wavemap - after perception - https://github.com/ethz-asl/wavemap
- [ ] Paper writing session
