### ISSUE TITLE
Running TODO List

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#667]
- [x] Training NeRF
- [x] Integrating Elevation Mapping Cupy
- [x] Fixing the calibration bugs on the box
- [x] Testing LiDAR calibration: https://github.com/ori-drs/diffcal/tree/grand_tour
- [x] Restructure the submodules into application modules after fixing other bugs
- [x] Fix undistortion with correct module
