### ISSUE TITLE
GrandTour Final URDF Update Changelist

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#840]
## Task Description:
Export a new version of the Box URDF including all components.
Reference URDF Export as dae:
https://github.com/ANYbotics/anymal_d_simple_description/tree/master/meshes

## Current State:
![image](https://github.com/user-attachments/assets/8cc9bb6c-e5ee-4b0d-a237-ed90ea7facac)

### Remove List:

- [ ] Cable pass trough was changed to the vertical one
- [ ] Glass in front of Alphasense Cameras is not needed

### Changes from Current State
- [ ] Prism Aluminium Extension modules missing (2x)
- [ ] 3D printed side outlets do not have holes
- [ ] Mounting module to ANYmal is not visible (Optional to add) 
- [ ] 3D Printed holder of  GPS Antenna Front
- [ ] Abstandshalter GPS Antenna Front
- [ ] GPS Antenna Front
- [ ] GPS Antenna Including Mount Back
- [ ] CPT Module
- [ ] Basilisk Module

## General
- [ ] The URDF should not include the Lasertracker T-Probe mount but the other plate
- [ ] The URDF should not include the current front Rollcage

## Colors (suggestion)

![IMG_8884](https://github.com/user-attachments/assets/e4d996ac-46bf-43ce-a933-0b25160d40fe)
- GPS Antenna White + Copper
- All 3D Printed parts simply back
- Hesai LiDAR (Black Middle for Glass and Silver)
- Livox LiDAR (Blue and Silver)
- Prism (Black and Orange)
- CPT7 fully Black
- Basisk fully Silver
Total Colors: 6
